### ISSUE TITLE
fog still broken on omaha beach

### ISSUE THREAD

**Issue by ghost** [MrRendroc/gldirect#2]
hi, i just tried your opengl dll but it didn't fix the moh aa beach fog. it still does the same thing that the normal opengl does on the game where you can see the bunkers at begining but as soon as you exit the landing craft the fog glitches and nothing is visible but the ocean and a few meters ahead until you move further up the beach when stuff comes back into view.

currently only r_farplane fixes the fog, well not really as i guess it pushes the fog away or something? i set it to 8250 and it's ok just has some flickering terrain on left and right in distance which i guess is usually hidden till you get closer.

also the menu is glitched with your dll, shows duplicate images and black bars.

oh i guess i should mention the following;

windows 11 x64 (latest)
amd radeon 6600 xt
gog version of the game

**Comment by MrRendroc** [comment]
Thanks for the feedback!  That may be a different issue than what this project is for.  The Omaha Beach level has some unique fog and may need a different solution.  _If you already have fog and the game works without using opengl32.dll, then you probably don't need it at all._
In your case, maybe this will help? 
https://www.youtube.com/watch?v=sVlK2BCBQVM&ab_channel=SapowiTz

This opengl32.dll is an updated version of the commonly-used gldirect5 that was last released having **_no fog at all_**, in _any_ level (including Omaha Beach).  It will enable fog for every map that originally had it.  It will not fix fog that pops on/off, glitches, or any other problems that were seen in the original game.

About the menu: this was a glitch seen in the earlier release of gldirect5; since this update only enables fog it won't fix that either, sorry.

**Comment by MrRendroc** [comment]
Not intended to fix Omaha Beach fog or menu.
